### PR TITLE
fix: tocFollow bug (see http://bitly.com/2KvhF3d)

### LINKED ISSUE #174: 2个问题
1. categories页无法显示所有分类
image
2.文章右侧的目录导航进度跟踪显示问题
参见https://xyq000.github.io/2017/08/24/Redis-%E6%8C%81%E4%B9%85%E5%8C%96/
页面拉到最底，右侧的目录导航条会停在倒数第二个标题上

### PR DESCRIPTION
**Pull request by JieJiSS**
After some deep investigation through JQuery's `.offset().top`, I realized there's another bug... and this PR should patch it.

(I could have fixed this bug in last PR...)

This should fix #174

### CODE REVIEW

**Comment by JieJiSS** [comment]
(Since I've just realized that the title will become part of commit log... So I removed colloquial words)

File: source/js/src/even.js [hunk 1]
```diff
@@ -111,7 +111,7 @@
 
     $(window).scroll(function () {
       var headerlinkTop = $.map($headerlink, function (link) {
-        return $(link).offset().top;
+        return $(window).scrollTop() + $(link).offset().top;
```
Comment (JieJiSS) [inline source/js/src/even.js]: Note that `$(window).scrollTop()` (as a getter) is more compatible than either `$(document.body).scrollTop()` or `$('html').scrollTop()`, since according to [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=766938) and [this comment](https://stackoverflow.com/questions/5371139/window-scrolltop-vs-document-scrolltop#comment-20034307) they won't work in Chrome.

**Comment by JieJiSS** [comment]
@ahonn After some other checks, I found that though this code snippet works well in Chrome & Safari, it is broken in FF, because FF's `$el.offset().top` is Chrome's `$(window).scrollTop() + $el.offset().top`

Is it acceptable if I use some methods to detect whether the user's browser is FF or not?

File: source/js/src/even.js [hunk 2]
```diff
@@ -106,12 +106,16 @@
...
     var HEADERFIX = 30;
+    var isFirefox = navigator.userAgent.toLowerCase().indexOf('firefox') > -1;
     var $toclink = $('.toc-link'),
       $headerlink = $('.headerlink');
 
     $(window).scroll(function () {
       var scrollTop = $(window).scrollTop();
       var headerlinkTop = $.map($headerlink, function (link) {
+        if(isFirefox) {
+          return $(link).offset().top;
```
Comment (JieJiSS) [inline source/js/src/even.js]: I believe this is a bug of jQuery

**Comment by JieJiSS** [comment]
Done. It's safe to merge now

File: source/js/src/even.js (hunk 2 above)
Comment (JieJiSS) [reply source/js/src/even.js]: Managed to fully understand the issue, and I'll try to explain it here.

The markdown renderer of `hexo-theme-even` will generate these codes for headers:

```html
<h2 id="测试标题">
  <a href="#测试标题" class="headerlink" title="测试标题"></a>
  测试标题
</h2>
```

Since `<a>` tag has no text, it is a transparent link.

Let's have a look at jQuery's `$.prototype.offset`:

```js
offset: function(a) {
  if (arguments.length)
    return void 0 === a ? this : this.each(function(b) {
      r.offset.setOffset(this, a, b)
    });
  var b, c, d, e, f = this[0];
  if (f)
    return f.getClientRects().length ? (d = f.getBoundingClientRect(),
    // (1)
    d.width || d.height ? (e = f.ownerDocument,
    c = Sb(e),
    b = e.documentElement,
    {
      // (2)
      top: d.top + c.pageYOffset - b.clientTop,
      left: d.left + c.pageXOffset - b.clientLeft
    // (3)
    }) : d) : {
      top: 0,
      left: 0
    }
}
```

In Chrome (or let's say, WebKit), this `<a class="headerlink">` is `0*0` pixels big, but in Firefox, it is `0*34.166`, which means that at point `(1)`, `d.width || d.height` evaluates to `false` in WebKit, and `true` in Firefox. Thus, WebKit browsers got to `(3)` and directly returns `d`, while Firefox goes to `(2)` and returns `d.top + c.pageYOffset - b.clientTop`. In this case, `c.pageYOffset` equals to `$(window).scrollTop()`, and that's why WebKit's `.top` = Firefox's `.top - $(window).scrollTop()`.

Maybe I'll write a blog about this later :-)

Comment (JieJiSS) [reply source/js/src/even.js]: Here comes the final solution: this **is** a bug of jQuery, but it has been fixed in the latest version of jQuery (I've tested that.), so you can either merge my PR to patch it or upgrade your `lib/jquery.min.js`'s version to the latest version.

Have a nice day :-)

**Comment by ahonn** [comment]
Graet. I think it would be better to upgrade jQuery. Can you help me to upgrading？
